---
  # - hosts: all
  #   become: yes
  #   roles:
  #    - common

  - hosts: staging
    #become: yes
    roles:
     - webserver

  # - hosts: jenkins
  #   become: yes
  #   roles:
  #     - role: geerlingguy.java
  #     - role: geerlingguy.jenkins
  #     - jenkinssetup
  #     - node