---
  
  # [DEPRECATION WARNING]: The 'restart' parameter causes instability. Use the
  # 'win_reboot' action conditionally on 'reboot_required' return value instead.
  # This feature will be removed in version 2.6. Deprecation warnings can be
  # disabled by setting deprecation_warnings=False in ansible.cfg.
  
  - name: Install IIS Web-Server with sub features and management tools
    win_feature:
      name: Web-Server
      state: present
      #restart: True
      include_sub_features: True
      include_management_tools: True

  - name: Install ASPNET 4.5
    win_feature:
      name: NET-Framework-45-ASPNET
      state: present       

  - name: chocolatey install .net FW 4.5.2
    win_chocolatey:
      name: dotnet4.5
      state: present

  - name: chocolatey install .net FW 4.6.1
    win_chocolatey:
      name: dotnet4.6.1
      state: present

  - name: Deploy default iisstart.htm file
    template:
      src: iisstart.j2
      dest: c:\inetpub\wwwroot\iisstart.htm

  # TODO Only reboot if necessary (see above...)
  - name: Reboot
    win_reboot:

  - name: Download appVeyor deployment agent
    win_shell: (new-object net.webclient).DownloadFile('https://www.appveyor.com/downloads/deployment-agent/latest/AppveyorDeploymentAgent.msi', 'AppveyorDeploymentAgent.msi')
    args:
      chdir: c:\
      creates: c:\AppveyorDeploymentAgent.msi

  # - name: Check if appVeyor agent is installed
  #   win_service:
  #     name: Appveyor.DeploymentAgent
  #     register: service_info

  - name: Install appVeyor deployment agent
    win_shell: msiexec /i AppveyorDeploymentAgent.msi /quiet /qn /norestart /log install.log ENVIRONMENT_ACCESS_KEY={{ appveyor_environment_access_key }} DEPLOYMENT_GROUP={{ appveyor_deployment_group }} >> c:\AppveyorDeploymentAgent.log
    args:
      chdir: c:\
      creates: install.log

  - name: Remove Default Web Site
    win_iis_website:
      name: "Default Web Site"
      state: absent
